<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Meeting\Module'                        => __DIR__ . '/Module.php',
    'Meeting\Controller\Main' => __DIR__ . '/src/Meeting/Controller/Main.php',
    'MeetingTest\Framework\TestCase'        => __DIR__ . '/tests/Meeting/Framework/TestCase.php',
    'MeetingTest\SampleTest'                => __DIR__ . '/tests/Meeting/SampleTest.php',
);