<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Secret\Module'                        => __DIR__ . '/Module.php',
    'Secret\Controller\MainController' => __DIR__ . '/src/Secret/Controller/MainController.php',
    'SecretTest\Framework\TestCase'        => __DIR__ . '/tests/Secret/Framework/TestCase.php',
    'SecretTest\SampleTest'                => __DIR__ . '/tests/Secret/SampleTest.php',
);