<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'School\Module'                        => __DIR__ . '/Module.php',
    'School\Controller\Main' => __DIR__ . '/src/School/Controller/Main.php',
    'SchoolTest\Framework\TestCase'        => __DIR__ . '/tests/School/Framework/TestCase.php',
    'SchoolTest\SampleTest'                => __DIR__ . '/tests/School/SampleTest.php',
);